version: '3.8'

services:
  app:
    build: .
    container_name: project
    restart: on-failure
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "5005:5005"
    env_file:
      - .env
    networks:
      - backend-net
    volumes:
      - ./config:/config
    command: [
      "java", "-jar", "app.jar",
      "--spring.redis.host=${SPRING_REDIS_HOST}",
      "--spring.redis.port=${SPRING_REDIS_PORT}"
    ]

  redis:
    image: redis:7-alpine
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - backend-net

  db:
    image: mysql:8.0
    container_name: spring-mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend-net

volumes:
  redis-data:
  mysql-data:

networks:
  backend-net:
    driver: bridge
